// _id: 63dbe8076f372352fd4c4b22

// 12 bytes id it's
  //4 bytes: timestamp
  //3 bytes: machine identifier
  //2 bytes: process identifier
  //3 bytes: counter

// 1 byte = 8 bits
// 2 ^ 8 = 256
// 2 ^ 24 = 16M

// This id here id generated by Driver
// So we don't want to wait for mongodb to create a id.
// Mongoose talk to mongodb driver and generate a objectId 

const mongoose = require('mongoose');

const id = new mongoose.Types.ObjectId();
console.log(id);
console.log(id.getTimestamp()); // to get time from ObjectId

const isValid = mongoose.Types.ObjectId.isValid('1234');
console.log(isValid);

